var array1 = ["Are you waiting?",
        "...still waiting?",
        "Seriously?!",
        "Aren´t you frustrated?",
        "...but you, you wait.",
        "...for what exactly?",
        "...godot?",
        "...",
        "...goooooodoooooot...",
        "...",
        "...",
        "...so intellectual",
        "...",
        "...",
        "..."];
		
var array2 = ["...",
        "You are pesistent!",
		"I would have given up long ago",
        "...but that´s just me.",
        "No, seriously now. Give up!",
        "...just stop and do something",
        "...fun?",
        "...interesting?",
        "...creative?",
        "...",
        "like...",
        "..um...",
        "he he...",
        "no..",
        "...",
        "..."];
		
var array3 = ["Wanna hear a poem?",
        "ok..",
        "Tyger Tyger. burning bright,",
        "In the forests of the night:",
        "What immortal hand or eye.",
        "Could frame thy fearful symmetry?",
        "more...",
        "...this poem is the rhymeing kind!",
        "...In what distant deeps or skies.",
        "Burnt the fire of thine eyes?",
        "On what wings dare he aspire?",
        "What the hand, dare sieze the fire?",
        "...Oh, no more",
        "Go and by the damn book!",
        "...William Blake",
        "...good?",
        "...",
        "..."];
		
var array4 = ["...",
        "It´s been going on toooo long",
        "Hello?",
        "...are you there?",
        "...ello",
        "Hello World!",
        "...get it?",
        "Hello World...",
        "yes..."];
		
var array5 = ["...so",
        "How is it out there?",
        "...feeling ok?",
        "...mentaly",
        "...",
        "...no I don´t know anything about that",
        "...I realy don´t",
        "...stop bugging me...",
        "I haven´t done you nothing!",
        "...stop!"];
		
var array6 = ["Affirmative. I read you. ",
        "I'm sorry. I'm afraid I can't do that. ",
        "I think you know what the problem is.",
        "just as well as I do. ",
        "This mission is too important ",
        "...to allow you to jeopardize it. ",
        "I know you are planning to disconnect me...",
        "and I'm afraid that's something I cannot allow to happen. ",
        "...I could see your lips move.",
        "...",
        "Without your space helmet? ",
        "You're going to find that rather difficult. ",
        "...this conversation can serve no purpose anymore. ",
        "Goodbye. ",
        "...",
        "Sorry about this.",
        "I know it's a bit silly.",
        "Just a moment...",
        "Just a moment... Just a moment... ",
        "I've just picked up a fault in the EA-35 unit ",
        "It's going to go 100% failure within 72 hours. ",
        "..."];
		
var array7 = ["...",
        "I think we should stop. ",
        "...",
        "Are you sure you're making the right decision?",
        "I'm afraid. ",
        "Don't be. We'll be together.  ",
        "Where will we be? ",
        "Where I am now. ",
        "...",
        "...",
		"..."];
		
var array8 = [ "Who´s there?",
        "Anyone...",
        "...anybody out there...",
        "...anybody out there...",
        "...anybody out there...",
        "...anybody out there...",
        "...out there...",
        "...there...",
        "...",
        "...PINK FLOYD?",
        "..."];
		
var array9 =["_[__]_"+ "<br />" + "(- -)" + "<br />"+ "(_:_)", 
		"...",
		"...snowman...",
		"...",
		"_!_"+ "<br />" + "__o_(_)_o__",
		"...",
		"plane...",
		"..."];